from setuptools import setup, find_packages

setup(
    name="hetcache",
    version="1.0.0",
    author="Tianyi Liu, Ye Lu, Linfeng Zhang, Chen Cai, Jianjun Gao, Yi Wang, Kim-Hui Yap, Lap-Pui Chau",
    description="HetCache: Training-Free Acceleration for Diffusion-Based Video Editing via Heterogeneous Caching",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/YOUR_USERNAME/HetCache",
    packages=find_packages(),
    python_requires=">=3.9",
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "transformers>=4.30.0",
        "einops>=0.6.0",
        "safetensors>=0.3.0",
        "modelscope>=1.9.0",
        "accelerate>=0.20.0",
        "scipy>=1.10.0",
        "scikit-learn>=1.2.0",
        "opencv-python>=4.7.0",
        "Pillow>=9.5.0",
        "numpy>=1.24.0",
        "tqdm>=4.65.0",
        "psutil>=5.9.0",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
